#!/bin/bash

function is_dvd {

	device="$(realpath $1)"
	test -z "$device" && return 1
	test -e "$device" || return 1
	test "$device" == "/dev/dvd" && return 0
	test "$device" == "/dev/sr0" && return 0
	test "${device: -3}" == "iso" && return 0
	test "${device: -8}" == "VIDEO_TS" && return 0

	return 1

}

function is_episode {

	video="$(realpath $1)"
	video="$(basename $video)"

	valid_pre=no
	test "${video:0:1}" == "1" && valid_pre=yes
	test "${video:0:1}" == "2" && valid_pre=yes
	test "${video:0:1}" == "3" && valid_pre=yes
	test "${video:0:1}" == "4" && valid_pre=yes
	test "${video:0:1}" == "5" && valid_pre=yes
	test "${video:0:1}" == "6" && valid_pre=yes
	test "$valid_pre" == "yes" || return 1

	valid_ext=no
	test "${video: -3}" == "mkv" && valid_ext=yes
	test "${video: -3}" == "mp4" && valid_ext=yes
	test "${video: -3}" == "mp4" && valid_ext=yes
	test "$valid_ext" == "yes" || return 1

	return 0

}

function check_episode {

	video="$(realpath $1)"
	video="$(basename $video)"

	ssh -q dlna [[ -f "~/Library/${video}" ]]

	return $?

}

for iso in $*; do

	is_dvd "$iso" || continue

	basename_iso="`basename \"$iso\"`"
	needs_encode=0

	for video in $(dvd_query "$iso" -f); do
		check_episode "$video" > /dev/null
		if [[ $? -eq 1 ]]; then needs_encode=1; fi
	done

	if [[ "$needs_encode" -eq 1 ]]; then
		echo "$basename_iso - DLNA missing episodes"
	else
		echo "$basename_iso - DLNA complete"
	fi
done
