#!/bin/bash

function is_episode {

	video="$(realpath $1)"
	video="$(basename $video)"

	valid_pre=no
	test "${video:0:1}" == "1" && valid_pre=yes
	test "${video:0:1}" == "2" && valid_pre=yes
	test "${video:0:1}" == "3" && valid_pre=yes
	test "${video:0:1}" == "4" && valid_pre=yes
	test "${video:0:1}" == "5" && valid_pre=yes
	test "${video:0:1}" == "6" && valid_pre=yes
	test "$valid_pre" == "yes" || return 1

	valid_ext=no
	test "${video: -3}" == "mkv" && valid_ext=yes
	test "${video: -3}" == "mp4" && valid_ext=yes
	test "${video: -3}" == "mp4" && valid_ext=yes
	test "$valid_ext" == "yes" || return 1

	return 0

}

function check_episode {

	video="$(realpath $1)"
	video="$(basename $video)"

	ssh -q dlna [[ -f "~/Library/${video}" ]]

	return $?

}

for video in $*; do

	video="$(realpath $video)"
	video="$(basename $video)"

	is_episode "$video" || continue

	check_episode "$video"
	if [[ $? -eq 0 ]]; then
		echo "${video} - DLNA file exists"
	else
		echo "${video} - DLNA file does not exist"
	fi

done
