#!/bin/bash
control_c() {
        exit 1
}
trap control_c SIGINT

dvds="$@"
if [[ -z "$dvds" ]]; then exit; fi

for iso in $dvds; do
	iso="$(realpath $iso)"
	dart --encode --verbose --skip-existing --test-existing --time --log-progress "$iso"
done
