#!/bin/bash
control_c() {
        exit 1
}
trap control_c SIGINT

dvds="$@"
if [[ -z "$dvds" ]]; then exit; fi

eject=""
if [[ $(uname -n) = "tobe.beandog.org" ]]; then
	eject="--eject"
fi

for iso in $dvds; do
	iso="$(realpath $iso)"
	ionice -c 2 -n 7 dart --encode --verbose --skip-existing --test-existing --time --log-progress "$iso" $eject
done
