#!/usr/bin/env bash
control_c() {
        exit 1
}
trap control_c SIGINT

dvds="$@"
if [[ -z "$dvds" ]]; then exit; fi

for iso in $dvds; do
	ionice -c 2 -n 7 dart --encode --verbose --skip-existing --test-existing --time --log-progress "$iso"
done
