#!/bin/bash

header="#!/bin/bash
control_c() {
        exit 1
}
trap control_c INT"

function is_dvd {

	device="$(realpath $1)"
	test -z "$device" && return 1
	test -e "$device" || return 1
	test "$device" == "/dev/dvd" && return 0
	test "$device" == "/dev/sr0" && return 0
	test "$device" == "/dev/sr1" && return 0
	test "${device: -3}" == "iso" && return 0
	test "${device: -8}" == "VIDEO_TS" && return 0
	test -d "${device}/BDMV" && return 0

	return 1

}

dvds="$*"
if [[ -z "$dvds" ]]; then dvds=/dev/sr0; fi

for iso in $dvds; do

	is_dvd "$iso" || continue

	filename="enc-`basename \"$iso\" .iso`.sh"
	test -e "$filename" && rm "$filename"
	content=$(dart --encode-info --skip-existing --time "$iso" | egrep "(^HandBrakeCLI|dvd_info|bluray_info|bluray_copy|mkvmerge|dvd_rip|ffmpeg|tout)")
	test -z "$content" && continue
	echo "$header" > "$filename"
	echo \# `ffmpeg -version | head -n 1` >> "$filename"
	echo "$content" >> "$filename"
	realpath=$(realpath "$filename")
	chmod +x "$filename"

done
