#!/bin/bash
cd /home/steve/Videos/Tails
random_iso="$(/home/steve/Videos/Rip-o-Matic/wheel-o-fun)"
test -z "$random_iso" && exit
random_iso_basename="$(basename $random_iso)"
is_encoding="$(pgrep -f "ffmpeg.+$random_iso_basename" -c)"
if [[ "$is_encoding" -ge 1 ]]; then echo "$random_iso_basename - DVD already being washed, spin again"; exit 1; fi

# Check to see if there are remaining episodes.
num_not_encoded=$(dart --episode-filenames "$random_iso" --skip-existing | wc -l)
if [[ "$num_not_encoded" -eq 0 ]]; then
	echo "$random_iso_basename - DVD already encoded, spin again"
	exit 1
fi

random_iso_log="/home/steve/Videos/Rip-o-Matic/catch-alot/$random_iso_basename.log"
touch "$random_iso_log"
cd /home/steve/Videos/Rip-o-Matic/bulky-bottles
encode_script="$(basename enc-$random_iso_basename .iso).sh"
/home/steve/bin/dvd_encode_script "$random_iso"
if [[ ! -e "$encode_script" ]]; then echo "no encode script created, exiting"; exit 1; fi
echo "[ `date` - $random_iso_basename ] - Wish-Wash, Encode Starting :)" >> /home/steve/Videos/Rip-o-Matic/event.log
ln -sf "$random_iso" .
cd ~/Videos/Tails
/home/steve/Videos/Rip-o-Matic/bulky-bottles/$encode_script 2>&1 | tee -a "$random_iso_log" 
echo "[ `date` - $random_iso_basename ] - Fluff-Puff, Encode Finished :D" >> /home/steve/Videos/Rip-o-Matic/event.log
echo "$random_iso can be safely removed" >> /home/steve/Videos/Rip-o-Matic/event.log
