#!/bin/bash
pgrep -l ^HandBrakeCLI -a | rev | cut -d ' ' -f 1 | rev | while read line; do emo --info "$line"; done
pgrep -l ^ffmpeg -a | rev | cut -d ' ' -f 1 | rev | while read line; do emo --info "$line"; done
