#!/usr/bin/php
<?php

	// Move ISOs not being encoded to current directory
	
	if($argc == 1)
		exit(0);

	$files = $argv;
	array_shift($files);
	$isos = preg_grep('/\.iso\/?$/', $files);

	if(!count($isos))
		return 0;
	
	foreach($isos as $iso) {

		if(!file_exists($iso))
			continue;

		$iso = realpath($iso);
		$basename = basename($iso);
		if(file_exists($basename))
			continue;
		$num_procs = exec("pgrep -a HandBrakeCLI | grep -c $basename", $output, $retval);
		if(!$num_procs)
			rename($iso, $basename);
	}
