#!/bin/bash

enabled=yes
archive_dvds=yes
rip_dvds=yes

event_log="/home/steve/Videos/Rip-o-Matic/event.log"

function usage {
	echo "spincycle -i <device> -t [bd|dvd|cd] [-l <volume name>]"
}

if [[ $# -eq 0 ]]; then usage; exit 1; fi

device=
disc_type=
volume=
while getopts i:t:l: opt; do
	case $opt in
		i)
			device=$OPTARG;;
		t)
			disc_type=$OPTARG;;
		l)
			volume=$OPTARG;;
	esac
done

if [[ "$enabled" == "no" ]]; then
	echo "[Info]" >> $event_log
	echo "spincycle disabled, ignoring $device" >> $event_log
	exit 0
fi

# echo device $device
# echo disc_type $disc_type
# echo volume $volume
if [[ -z "$device" && -z "$disc_type" ]]; then usage; exit 1; fi

if [[ "$disc_type" == "bd" ]]; then exit 0; fi

cd /home/steve/Media/Laundry-Basket
# cd /home/steve/Media/Storage-Closet
# cd /home/steve/Media/Laundry-Basket/On-Deck

event_log="/home/steve/Videos/Rip-o-Matic/event.log"
dev_basename=$(basename $device)
dvdbackup_log="/home/steve/Videos/Rip-o-Matic/dvdbackup.log"
if [[ "$device" == "/dev/sr1" ]]; then
	dvdbackup_log="/home/steve/Videos/Rip-o-Matic/dvdbackup.sr1.log"
elif [[ "$device" == "/dev/sr2" ]]; then
	dvdbackup_log="/home/steve/Videos/Rip-o-Matic/dvdbackup.sr2.log"
fi

echo "[ `date` $device - $volume ] UDEV Event Triggered" >> $event_log
dvd_drive_status $device
if [[ $? -ne 4 ]]; then exit 0; fi
sleep 2s

dvd_eject -t $device

if [[ "$disc_type" == "dvd" ]]; then
	echo "[ `date` $device - $volume ] DVD Detected" >> $event_log
fi

test $archive_dvds == "yes" && /home/steve/bin/dart --info $device >> $event_log

if [[ "$rip_dvds" == "yes" ]] && [[ "$disc_type" == "dvd" ]]; then

	final_iso_filename="$(/home/steve/bin/dart --iso-filename $device)"
	dvdbackup_dir_arg="$(basename $final_iso_filename .iso).R1p"

	if [[ -e "$final_iso_filename" ]]; then
		echo "[ `date ` $device - $volume ] ISO Found" >> $event_log
		eject $device
		exit 0
	elif [[ -e "$dvdbackup_dir_arg" ]]; then
		echo "[ `date ` $device - $volume ] Partial RIP Found" >> $event_log
		sudo beep -r 3
		eject $device
		exit 0
	else
		echo "[ `date` $device - $volume ] DVD Ripping" >> $event_log
		echo "[ `date` $device - $volume ] DVD Ripping" >> $dvdbackup_log
		dvdbackup -M -p -i $device -n "$dvdbackup_dir_arg" 2>&1 >> $dvdbackup_log
		echo "[ `date` $device - $volume ] DVD Ripped" >> $event_log
		eject $device
		echo "[ `date` $device - $volume ] DVD Ejected" >> $event_log
		/home/steve/bin/dart --rename-iso "$dvdbackup_dir_arg"
	fi

fi

if [[ "$archive_dvds" == "yes" ]] && [[ "$rip_dvds" == "no" ]]; then eject $device; exit 0; fi
